language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: U0t61S7I6X8nChsalAurLDXLw6WW44DPb2vpWXZjzDuWq1R/uMOdtjMK1gelM0uDXVS/U+Q2ZiTswDIVynYrQeTtNgjls4br6VpFWZ3XDvBPBJin4VOEx6mnCBi3RgYEXQ+lUTfOIQgs+6Q7HUJgLDRin5zEIekNroJfKOOiD/B2ZGsFhNDjzBwleCi6exYmoKtc+vSg1vl1Lmvw5VSR+WQGsEFJUrcruxsWliG94rIFelLg7aLuMF6+MdJPidarA65JyxZeymZUe5T45kMRUtHtENxEh8k9xvpH6NS8U/KMucqUnjbASOfFCRAxBzVp6fnud0LC/vNnvzZDVAXJHQYKo4rP7VWJwnTqqoUq4s9iriYnz7mQAZm11uFYF0NgJJ6rJHVBbI1rM3RrKYjXliiTmvfprV0RTcRttKWZdJ+N119SG2t6Zyfey4ITHdkI3A2qfXx6zF61WkXhyXa6YEb5uaTjScMycD+ng7AwbaOvCJ74O6BlqIHsYPkXGRp9/gLTAOcbAhKQG6A7Q51SBPPrtNmBkpbHeOXTfAteR/Cfyts+czsdSk+VYtJJx3r+RowXu+27xkUEErhAGlPvOOOAmYrapLvzQ0qvmBfHwdmI0D+9/5BO8AICV6yDg3TnLv8GRL8aQwsytAjyV6c20FwWL6COHun0Ql46cliAzkA=

notifications:
  email: false
